import React, {useEffect,useMemo,useState} from 'react';
import {ResponsiveContainer,Sankey,Tooltip} from 'recharts';
import {Activity,AlertTriangle,ArrowDownRight,ArrowUpRight,Download,GitCompareArrows,Landmark,RefreshCw,Search} from 'lucide-react';

const brl=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',notation:'compact',maximumFractionDigits:1}).format(n||0);
const riskClass={Alto:'high','Médio':'medium',Baixo:'low'};
function Kpi({icon:Icon,label,value,note,tone}){return <div className="card kpi"><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div><Icon className={tone}/></div>}
function Select({label,value,setValue,options}){return <label><span>{label}</span><select value={value} onChange={e=>setValue(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
export default function App(){
 const [rows,setRows]=useState([]),[meta,setMeta]=useState({});
 const [rp,setRp]=useState('Todos'),[risk,setRisk]=useState('Todos'),[q,setQ]=useState('');
 const load=async()=>{const [a,b]=await Promise.all([fetch('./data/movimentacoes.json'),fetch('./data/metadata.json')]);setRows(await a.json());setMeta(await b.json())};
 useEffect(()=>{load().catch(console.error)},[]);
 const filtered=useMemo(()=>rows.filter(x=>(rp==='Todos'||x.instrumento===rp)&&(risk==='Todos'||x.risco===risk)&&`${x.origem} ${x.destino} ${x.autor}`.toLowerCase().includes(q.toLowerCase())),[rows,rp,risk,q]);
 const total=useMemo(()=>({c:filtered.reduce((s,x)=>s+x.cancelado,0),a:filtered.reduce((s,x)=>s+x.acrescido,0),h:filtered.filter(x=>x.risco==='Alto').length}),[filtered]);
 const sankey=useMemo(()=>{const L=[...new Set(filtered.map(x=>x.origem))],M=[...new Set(filtered.map(x=>x.instrumento))],R=[...new Set(filtered.map(x=>x.destino))],nodes=[...L,...M,...R].map(name=>({name})),idx=Object.fromEntries(nodes.map((n,i)=>[n.name,i])),agg=(keys,val)=>{const z={};filtered.forEach(x=>{const k=keys.map(y=>x[y]).join('|');z[k]=(z[k]||0)+x[val]});return z};const one=agg(['origem','instrumento'],'cancelado'),two=agg(['instrumento','destino'],'acrescido');return {nodes,links:[...Object.entries(one).map(([k,value])=>{const[a,b]=k.split('|');return{source:idx[a],target:idx[b],value}}),...Object.entries(two).map(([k,value])=>{const[a,b]=k.split('|');return{source:idx[a],target:idx[b],value}})]}},[filtered]);
 const csv=()=>{const h='origem,destino,instrumento,autor,cancelado,acrescido,risco\n',body=filtered.map(x=>[x.origem,x.destino,x.instrumento,x.autor,x.cancelado,x.acrescido,x.risco].map(v=>`"${v}"`).join(',')).join('\n'),u=URL.createObjectURL(new Blob([h+body],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='movimentacoes-cmo.csv';a.click();URL.revokeObjectURL(u)};
 return <><header><div className="brand"><GitCompareArrows/><div><b>Rastreador CMO</b><small>Orçamento e Legislativo</small></div></div><div className="status"><Activity/> {meta.fonte||'Carregando'} • {meta.atualizado_em||''}</div><button onClick={load}><RefreshCw/>Atualizar</button></header><main>
 <section className="hero"><div><p><Landmark/> Comissão Mista de Orçamento</p><h1>Como o Congresso alterou o orçamento?</h1><span>Compare fases, identifique cancelamentos e acréscimos e acompanhe RP6, RP7 e RP8.</span></div><button className="primary" onClick={csv}><Download/>Baixar dados</button></section>
 {meta.demonstrativo&&<div className="notice"><AlertTriangle/> Base demonstrativa. Execute o pipeline em R para produzir dados oficiais.</div>}
 <section className="filters card"><Select label="Emenda" value={rp} setValue={setRp} options={['Todos','RP6','RP7','RP8']}/><Select label="Risco" value={risk} setValue={setRisk} options={['Todos','Alto','Médio','Baixo']}/><label className="search"><span>Buscar programação</span><div><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Origem, destino ou autor"/></div></label></section>
 <section className="kpis"><Kpi icon={ArrowDownRight} tone="rose" label="Cancelamentos" value={brl(total.c)} note="Fase-base → fase comparada"/><Kpi icon={ArrowUpRight} tone="green" label="Acréscimos" value={brl(total.a)} note="Movimentações positivas"/><Kpi icon={GitCompareArrows} tone="blue" label="Movimentações" value={filtered.length} note="Registros após filtros"/><Kpi icon={AlertTriangle} tone="violet" label="Alertas prioritários" value={total.h} note="Critério configurável"/></section>
 <section className="grid"><div className="card chart"><h2>Fluxo das modificações</h2><p>Cancelamentos → tipo de emenda → destino</p><div className="sankey">{filtered.length>0&&<ResponsiveContainer><Sankey data={sankey} nodePadding={24} nodeWidth={14} link={{stroke:'#60a5fa',strokeOpacity:.38}} margin={{top:20,right:120,bottom:20,left:120}}><Tooltip formatter={brl}/></Sankey>}</div></div><aside className="card"><h2>Fases monitoradas</h2>{['Projeto do Executivo','Relatórios setoriais','Relatório final da CMO','Autógrafo'].map((x,i)=><div className="phase" key={x}><i className={i<3?'done':''}/><div><b>{x}</b><small>{i===2?'Fase comparada atual':i<2?'Disponível':'Pendente'}</small></div></div>)}</aside></section>
 <section className="card table"><h2>Movimentações com maior impacto</h2><div className="scroll"><table><thead><tr><th>Origem</th><th>Destino</th><th>Emenda</th><th>Cancelado</th><th>Acrescido</th><th>Alerta</th></tr></thead><tbody>{[...filtered].sort((a,b)=>b.cancelado-a.cancelado).map(x=><tr key={x.id}><td>{x.origem}</td><td>{x.destino}</td><td><b className="rp">{x.instrumento}</b></td><td className="neg">{brl(x.cancelado)}</td><td className="pos">{brl(x.acrescido)}</td><td><b className={`risk ${riskClass[x.risco]}`}>{x.risco}</b></td></tr>)}</tbody></table></div></section>
 <footer>Dados: {meta.fonte||'SIOP'} • Exercício {meta.exercicio||''} • Metodologia em METODOLOGIA.md</footer>
 </main></>}
